AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      [
        c4.large,
        c4.xlarge,
        c4.2xlarge,
        c4.4xlarge,
        c4.8xlarge,
        c5.large,
        c5.xlarge,
        c5.2xlarge,
        c5.4xlarge,
        c5.9xlarge,
        c5.12xlarge,
        c5.18xlarge,
        c5.24xlarge,
        c5a.large,
        c5a.xlarge,
        c5a.2xlarge,
        c5a.4xlarge,
        c5a.8xlarge,
        c5a.12xlarge,
        c5a.16xlarge,
        c5a.24xlarge,
        c5ad.large,
        c5ad.xlarge,
        c5ad.2xlarge,
        c5ad.4xlarge,
        c5ad.8xlarge,
        c5ad.12xlarge,
        c5ad.16xlarge,
        c5ad.24xlarge,
        c5d.large,
        c5d.xlarge,
        c5d.2xlarge,
        c5d.4xlarge,
        c5d.9xlarge,
        c5d.12xlarge,
        c5d.18xlarge,
        c5d.24xlarge,
        c5n.large,
        c5n.xlarge,
        c5n.2xlarge,
        c5n.4xlarge,
        c5n.9xlarge,
        c5n.18xlarge,
        c6a.large,
        c6a.xlarge,
        c6a.2xlarge,
        c6a.4xlarge,
        c6a.8xlarge,
        c6a.12xlarge,
        c6a.16xlarge,
        c6a.24xlarge,
        c6a.32xlarge,
        c6a.48xlarge,
        c6g.medium,
        c6g.large,
        c6g.xlarge,
        c6g.2xlarge,
        c6g.4xlarge,
        c6g.8xlarge,
        c6g.12xlarge,
        c6g.16xlarge,
        c6gd.medium,
        c6gd.large,
        c6gd.xlarge,
        c6gd.2xlarge,
        c6gd.4xlarge,
        c6gd.8xlarge,
        c6gd.12xlarge,
        c6gd.16xlarge,
        c6gn.medium,
        c6gn.large,
        c6gn.xlarge,
        c6gn.2xlarge,
        c6gn.4xlarge,
        c6gn.8xlarge,
        c6gn.12xlarge,
        c6gn.16xlarge,
        c6i.large,
        c6i.xlarge,
        c6i.2xlarge,
        c6i.4xlarge,
        c6i.8xlarge,
        c6i.12xlarge,
        c6i.16xlarge,
        c6i.24xlarge,
        c6i.32xlarge,
        c7g.medium,
        c7g.large,
        c7g.xlarge,
        c7g.2xlarge,
        c7g.4xlarge,
        c7g.8xlarge,
        c7g.12xlarge,
        c7g.16xlarge,
        c7gd.medium,
        c7gd.large,
        c7gd.xlarge,
        c7gd.2xlarge,
        c7gd.4xlarge,
        c7gd.8xlarge,
        c7gd.12xlarge,
        c7gd.16xlarge,
        c7gn.medium,
        c7gn.large,
        c7gn.xlarge,
        c7gn.2xlarge,
        c7gn.4xlarge,
        c7gn.8xlarge,
        c7gn.12xlarge,
        c7gn.16xlarge,
        c7i.large,
        c7i.xlarge,
        c7i.2xlarge,
        c7i.4xlarge,
        c7i.8xlarge,
        c7i.12xlarge,
        c7i.16xlarge,
        c7i.24xlarge,
        c7i.48xlarge,
        m4.large,
        m4.xlarge,
        m4.2xlarge,
        m4.4xlarge,
        m4.10xlarge,
        m4.16xlarge,
        m5.large,
        m5.xlarge,
        m5.2xlarge,
        m5.4xlarge,
        m5.8xlarge,
        m5.12xlarge,
        m5.16xlarge,
        m5.24xlarge,
        m5a.large,
        m5a.xlarge,
        m5a.2xlarge,
        m5a.4xlarge,
        m5a.8xlarge,
        m5a.12xlarge,
        m5a.16xlarge,
        m5a.24xlarge,
        m6a.large,
        m6a.xlarge,
        m6a.2xlarge,
        m6a.4xlarge,
        m6a.8xlarge,
        m6a.12xlarge,
        m6a.16xlarge,
        m6a.24xlarge,
        m6a.32xlarge,
        m6a.48xlarge,
        m7a.medium,
        m7a.large,
        m7a.xlarge,
        m7a.2xlarge,
        m7a.4xlarge,
        m7a.8xlarge,
        m7a.12xlarge,
        m7a.16xlarge,
        m7a.24xlarge,
        m7a.32xlarge,
        m7a.48xlarge,
        t2.nano,
        t2.micro,
        t2.small,
        t2.medium,
        t2.large,
        t2.xlarge,
        t2.2xlarge,
        t3.nano,
        t3.micro,
        t3.small,
        t3.medium,
        t3.large,
        t3.xlarge,
        t3.2xlarge,
        t3a.nano,
        t3a.micro,
        t3a.small,
        t3a.medium,
        t3a.large,
        t3a.xlarge,
        t3a.2xlarge,
        t4g.nano,
        t4g.micro,
        t4g.small,
        t4g.medium,
        t4g.large,
        t4g.xlarge,
        t4g.2xlarge
      ]

Mappings:
  Constants:
    Ec2:
      ImageId: '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64}}'
    Vpc:
      CidrBlock: 10.0.0.0/16
      PublicSubnetCidrBlock: 10.0.0.0/24

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !FindInMap [Constants, Vpc, CidrBlock]
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName
  VpcIgw:
    Type: AWS::EC2::InternetGateway
  VpcIgwAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref VpcIgw
      VpcId: !Ref Vpc

  VpcPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
  VpcPublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref VpcPublicRouteTable
      GatewayId: !Ref VpcIgw
      DestinationCidrBlock: 0.0.0.0/0
    DependsOn:
      - VpcIgwAttachment

  VpcPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: !FindInMap [Constants, Vpc, PublicSubnetCidrBlock]
  VpcPublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref VpcPublicRouteTable
      SubnetId: !Ref VpcPublicSubnet

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref Vpc
      GroupDescription: cloud9-alternative
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: -1

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - !Join
          - ''
          - - 'arn:'
            - Ref: 'AWS::Partition'
            - ':iam::aws:policy/AdministratorAccess'
  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - !Ref InstanceRole

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [Constants, Ec2, ImageId]
      InstanceType: !Ref InstanceType
      NetworkInterfaces:
        - SubnetId: !Ref VpcPublicSubnet
          AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          GroupSet:
            - !Ref InstanceSecurityGroup
      IamInstanceProfile: !Ref InstanceProfile
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName
      UserData: !Base64 |
        #!/bin/bash

        set -o errexit
        set -o nounset
        set -o pipefail
        set -o xtrace

        # Install Visual Studio Code
        # Reference: https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions
        sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
        echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" | sudo tee /etc/yum.repos.d/vscode.repo > /dev/null
        dnf check-update
        sudo dnf install -y code
